### ISSUE TITLE
Add command permissions

### ISSUE THREAD

**Issue by Satont** [Satont/twobit#15]
Make possible set permission of commands.

Broadcaster > Moderator > Subscriber > Vip > Viewer

**Comment by AlexWayfer** [comment]
> Broadcaster

Is it better than `Streamer`? :thinking:

**Comment by Satont** [comment]
> > Broadcaster
> 
> Is it better than `Streamer`? 🤔

Same as streamer, i called this as` broadcaster` because twitch chat message payload returns `broadcaster` badge, so this way better for understand

**Comment by AlexWayfer** [comment]
> i called this as broadcaster because twitch chat message payload returns broadcaster badge, so this way better for understand

Oh, yeah, this is an argument.
