### ISSUE TITLE
Add pagination for `!top` command

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/twobit#81]
For now we're having only `!top %type%`, like `!top time`, and bot is returning the first 10 users.

I think, `!top` command can accept an argument as page number, like `!top time 2`, and bot can return 11–20th users.

**Comment by Satont** [comment]
Actually i think move part of command filters like `$top_time` to already builted in bot commands.
But i need think about how to do that customizable.

**Comment by Satont** [comment]
Done. Simple set page of command in your message query.

Like `!top time 1` , `!top time 2`, e.t.c
